language: cpp
compiler: gcc
os: linux

sudo: required

notifications:
    email: false

before_script:
    - wget www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.gz
    - tar -xvf /tmp/sfml.tar.gz
    - sudo mv SFML-2.4.2/* /usr/

script: g++ src/*.cpp -Wall -lsfml-graphics -lsfml-window -lsfml-system

addons:
    apt:
        packages:
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libudev-dev
            - libfreetype6-dev
            - libglew1.5-dev
            - libjpeg8-dev
            - libopenal-dev
            - libsndfile1-dev
